name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js ${{ inputs.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
